// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpnPRetX380UNhOuqUyBPqra4j-ZBbPPM',
    appId: '1:962610677448:web:219d93838870bede8247fd',
    messagingSenderId: '962610677448',
    projectId: 'namer-startup',
    authDomain: 'namer-startup.firebaseapp.com',
    storageBucket: 'namer-startup.appspot.com',
    measurementId: 'G-5HKK78GK78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNWVJw78tjlymAR_cUlkg9uF-n5HEi5R0',
    appId: '1:962610677448:android:3e81e09ee10e679b8247fd',
    messagingSenderId: '962610677448',
    projectId: 'namer-startup',
    storageBucket: 'namer-startup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2dwMmaD0c2bpLsB0rHx2YG4q3oGTboYs',
    appId: '1:962610677448:ios:d57b8bab88e8a1d68247fd',
    messagingSenderId: '962610677448',
    projectId: 'namer-startup',
    storageBucket: 'namer-startup.appspot.com',
    iosClientId: '962610677448-6pt4f360pf900095ikb9t581utl5b6vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupNamer',
  );
}
